### ISSUE TITLE
Unable to mock OmniAuth

### ISSUE THREAD

**Issue by jrdufresne** [Pioneer-Valley-Books/rails-response-dumper#20]
I am attempting to dump a response after first authenticating with the following setup:

```
  OmniAuth.config.test_mode = true
  OmniAuth.config.mock_auth[:google_oauth2] = OmniAuth::AuthHash.new({
    info: {
      email: 'test@pvep.com',
    },
  })

  get '/auth/google_oauth2/callback'
```

Since the above requires a request that returns a `302` the dump is failing during validation:

```
$ bundle exec rails-response-dumper
bundler: failed to load command: rails-response-dumper (/Users/jrdufresne/.gem/ruby/3.0.0/bin/rails-response-dumper)
/Users/jrdufresne/.gem/ruby/3.0.0/gems/rails-response-dumper-2.1.0/bin/rails-response-dumper:108:in `block (3 levels) in run_dumps': Dumped response has unexpected status code 302 Found (expected 200) (RuntimeError)
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/rails-response-dumper-2.1.0/bin/rails-response-dumper:106:in `each'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/rails-response-dumper-2.1.0/bin/rails-response-dumper:106:in `each_with_index'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/rails-response-dumper-2.1.0/bin/rails-response-dumper:106:in `block (2 levels) in run_dumps'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/rails-response-dumper-2.1.0/bin/rails-response-dumper:85:in `each'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/rails-response-dumper-2.1.0/bin/rails-response-dumper:85:in `block in run_dumps'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/rails-response-dumper-2.1.0/bin/rails-response-dumper:84:in `each'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/rails-response-dumper-2.1.0/bin/rails-response-dumper:84:in `run_dumps'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/rails-response-dumper-2.1.0/bin/rails-response-dumper:125:in `<top (required)>'
        from /Users/jrdufresne/.gem/ruby/3.0.0/bin/rails-response-dumper:23:in `load'
        from /Users/jrdufresne/.gem/ruby/3.0.0/bin/rails-response-dumper:23:in `<top (required)>'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/bundler-2.2.33/lib/bundler/cli.rb:479:in `exec'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/bundler-2.2.33/lib/bundler/cli.rb:31:in `dispatch'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/bundler-2.2.33/lib/bundler/cli.rb:25:in `start'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/bundler-2.2.33/exe/bundle:49:in `block in <top (required)>'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/bundler-2.2.33/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        from /Users/jrdufresne/.gem/ruby/3.0.0/gems/bundler-2.2.33/exe/bundle:37:in `<top (required)>'
        from /Users/jrdufresne/.gem/ruby/3.0.0/bin/bundle:23:in `load'
        from /Users/jrdufresne/.gem/ruby/3.0.0/bin/bundle:23:in `<main>'
```

Introduced in https://github.com/Pioneer-Valley-Books/rails-response-dumper/commit/5ac4e241138932955846583a15394b74395a3a1b

**Comment by jrdufresne** [comment]
Thinking a solution could be to add a setup method that gets executed before each `*_dump` method. This wouldn't go through the same assertions as the `*_dump`.

**Comment by jrdufresne** [comment]
This can now be avoided by using multiple status codes. See https://github.com/Pioneer-Valley-Books/rails-response-dumper/commit/7fcc759d9b4ab91787de94064829f5a2f9644d29 for more details
